[package]
name = "dychatat"
version = "0.1.0"
authors = ["Peter Williams <pwil3058@gmail.com>"]
edition = "2018"

[dependencies]
crypto-hash = "0.3.3"
fs2 = "0.4.3"
hex = "0.3.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8.9"
snap = "0.2.5"
tempdir = "0.3.7"
